.PHONY: all clean fclean

all:
	$(MAKE) -C get_next_line
	$(MAKE) -C libft

clean:
	$(MAKE) -C get_next_line clean
	$(MAKE) -C libft clean

fclean:
	$(MAKE) -C get_next_line fclean
	$(MAKE) -C libft fclean
